export const safeMock = [
  {
    name: 'Safe1',
    id: '0x123',
    imgSrc: '',
    description: 'Safe1 desc',
    isLocked: false,
    owner: '0x123',
    user: '0x456',
  },
  {
    name: 'Safe2',
    id: '0x123',
    imgSrc: '',
    description: 'Safe2 desc',
    isLocked: false,
    owner: '0x123',
    user: '0x456',
  },
  {
    name: 'Safe3',
    id: '0x123',
    imgSrc: '',
    description: 'Safe3 desc',
    isLocked: false,
    owner: '0x123',
    user: '0x456',
  },
  {
    name: 'Safe4',
    id: '0x123',
    imgSrc: '',
    description: 'Safe4 desc',
    isLocked: false,
    owner: '0x123',
    user: '0x456',
  },
  {
    name: 'Safe5',
    id: '0x123',
    imgSrc: '',
    description: 'Safe5 desc',
    isLocked: false,
    owner: '0x123',
    user: '0x456',
  },
  {
    name: 'Safe6',
    id: '0x123',
    imgSrc: '',
    description: 'Safe5 desc',
    isLocked: false,
    owner: '0x123',
    user: '0x456',
  },
  {
    name: 'Safe7',
    id: '0x123',
    imgSrc: '',
    description: 'Safe5 desc',
    isLocked: false,
    owner: '0x123',
    user: '0x456',
  }
]